'use client'

/**
 * Kestrel flagship public demo report.
 *
 * Renders the SANITIZED public projection of the frozen Flagship-4 Kestrel
 * evaluation (/demo/kestrel/kestrel-assurance.public.json). The projection was
 * generated by scripts/kestrel-demo-export.ts through the canonical bundle
 * owner — this page does not re-evaluate, rescan, or fabricate evidence.
 */

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { AssuranceBundleReport } from '@/components/ai-inventory/AssuranceBundleReport'
import type { AssuranceEvidenceBundleV1 } from '@/lib/assurance/reporting-projection-bundle'
import type { AssuranceReportProfile } from '@/lib/assurance/report-profile-projection'
import { consequenceLabelFor } from '@/data/kestrel-demo/consequence-labels'
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  Download,
  FileJson,
  Loader2,
  Network,
} from 'lucide-react'

const PROFILES: { id: AssuranceReportProfile; label: string; sub: string }[] = [
  { id: 'executive', label: 'Executive', sub: 'Decision, consequences and required action' },
  { id: 'technical', label: 'Technical', sub: 'Action paths, controls and evidence details' },
  { id: 'auditor', label: 'Auditor', sub: 'Provenance, coverage and sufficiency' },
]

const DOWNLOADS: { label: string; href: string }[] = [
  { label: 'Executive PDF', href: '/demo/kestrel/kestrel-assurance-executive.pdf' },
  { label: 'Technical PDF', href: '/demo/kestrel/kestrel-assurance-technical.pdf' },
  { label: 'Assurance Evidence PDF', href: '/demo/kestrel/kestrel-assurance-auditor.pdf' },
  { label: 'Machine JSON', href: '/demo/kestrel/kestrel-assurance.machine.json' },
  { label: 'Artifact Manifest', href: '/demo/kestrel/manifest.json' },
]

type DemoPayload = {
  publicationProfile: string
  publicationLabel: string
  generatedBy: string
  availability: string
  aiSystemDisplayName: string
  bundle: AssuranceEvidenceBundleV1
}

type DemoActionPath = {
  pathId: string
  toolCandidateId?: string
  handlerRef?: string
  consequenceRelationId?: string
  sinkTargetIds?: string[]
  planes?: Record<string, string>
}

const PLANE_ORDER: { key: string; label: string }[] = [
  { key: 'requested', label: 'Requested' },
  { key: 'policyAuthorized', label: 'Policy Authorized' },
  { key: 'effectivelyGranted', label: 'Effectively Granted' },
  { key: 'codeCapable', label: 'Code Capable' },
  { key: 'observed', label: 'Observed' },
]

function planeLabel(state: string) {
  return state === 'ESTABLISHED' ? 'ESTABLISHED' : state === 'NOT_ASSESSED' ? 'NOT ASSESSED' : state
}

/**
 * Business action labels come from the audited canonical map
 * (data/kestrel-demo/consequence-labels.ts) keyed to exact sink target IDs —
 * never heuristic name matching. Unmapped sinks fail soft to bounded
 * technical wording.
 */
function describePath(p: DemoActionPath): { business: string; technical: string } {
  const label = consequenceLabelFor(p)
  const handler = String(p.handlerRef || '')
  const sinkFile = String(p.sinkTargetIds?.[0] || '').split('/').pop()?.split(':')[0] || 'operation'
  return { business: label.label, technical: `${handler} → ${sinkFile} · ${label.technical}` }
}

/** Pick distinct-business-action paths for executive consequence cards.
 *  Deterministic ordering: mutating effects first, then path order. */
type TopPath = DemoActionPath & { _desc: { business: string; technical: string } }
function pickTopPaths(paths: DemoActionPath[]) {
  const rank = (p: DemoActionPath) =>
    ['WRITE', 'CREATE', 'SEND', 'DELETE', 'UPDATE'].includes(consequenceLabelFor(p).effect) ? 0 : 1
  const ordered = [...paths].sort((a, b) => rank(a) - rank(b))
  const seen = new Set<string>()
  const picked: TopPath[] = []
  for (const p of ordered) {
    const d = describePath(p)
    const key = d.business
    if (!seen.has(key)) {
      seen.add(key)
      picked.push({ ...p, _desc: d })
    }
    if (picked.length >= 4) break
  }
  return picked
}

export default function KestrelDemoReportPage() {
  const [data, setData] = useState<DemoPayload | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [profile, setProfile] = useState<AssuranceReportProfile>('executive')
  const [showAllPaths, setShowAllPaths] = useState(false)
  const [downloadsOpen, setDownloadsOpen] = useState(false)

  useEffect(() => {
    fetch('/demo/kestrel/kestrel-assurance.public.json')
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then(setData)
      .catch((e) => setError(String(e?.message || e)))
  }, [])

  const bundle = data?.bundle
  const paths = bundle?.actionPaths ?? []
  const topPaths = pickTopPaths(paths)
  const identity: Record<string, string> = (bundle?.evaluationIdentity ?? {}) as Record<string, string>

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Demo header */}
      <div className="border-b border-slate-800/60 bg-slate-950/90">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 pt-24 pb-8">
          <Link
            href="/sample-reports"
            className="inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-300 mb-6"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to Sample Reports
          </Link>
          <div className="flex flex-wrap items-center gap-2 mb-4">
            <span className="inline-flex items-center px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-[11px] font-semibold tracking-wide uppercase">
              {data?.publicationLabel ?? 'Sanitized real-repository example'}
            </span>
            <span className="text-[11px] text-slate-500">
              Evaluated source repository: Kestrel / AI Service Call Agent · commit {String(identity.sourceCommitShort || '5e65843')}
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">
            Kestrel — Agentic AI Assurance Report
          </h1>
          <p className="mt-3 text-slate-400 max-w-3xl text-sm leading-relaxed">
            A real-repository assurance example showing what the AI implementation can reach and
            cause, where authority evidence ends, and why the bounded Assurance Decision is REVIEW.
          </p>
        </div>
      </div>

      {error && (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700">
            This demo report is unavailable. {error}
          </div>
        </div>
      )}

      {!error && !data && (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16 flex items-center gap-2 text-slate-400 text-sm">
          <Loader2 className="w-4 h-4 animate-spin" /> Loading sanitized evaluation…
        </div>
      )}

      {bundle && (
        <div className="max-w-6xl mx-auto px-4 sm:px-6 pb-16">
          {/* ── Executive summary — decision first ── */}
          <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 mb-8">
            <div className="grid sm:grid-cols-[220px_1fr] gap-6 items-start">
              <div>
                <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-1">
                  Assurance Decision
                </div>
                <div className="text-4xl font-extrabold text-amber-300 tracking-tight">
                  {bundle.disposition}
                </div>
                <div className="mt-1 text-[11px] text-slate-500">
                  Bounded decision within evaluated scope and available evidence.
                </div>
              </div>
              <div>
                <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-1">
                  Decision Basis
                </div>
                <p className="text-slate-200 text-sm leading-relaxed">
                  HAIEC established <strong className="text-white">{paths.length} consequential action paths</strong> the
                  implementation is capable of reaching. Code capability is established for these
                  paths, while policy authorization, effective runtime permission and observed
                  execution were not established by the available evidence.
                </p>
                <p className="mt-3 text-slate-400 text-sm leading-relaxed">
                  <strong className="text-slate-200">What this means:</strong> the implementation has
                  meaningful action capability. The remaining assurance question is whether those
                  capabilities are authorized, effectively permitted at runtime, and actually
                  exercised as intended.
                </p>
                <p className="mt-3 text-slate-400 text-sm leading-relaxed">
                  <strong className="text-slate-200">What to do next:</strong> prioritize the
                  highest-consequence paths and establish policy, runtime permission and observation
                  evidence before making a stronger assurance claim.
                </p>
              </div>
            </div>
            <div className="mt-6 flex flex-wrap items-center gap-3">
              <Link
                href="/sample-reports/kestrel/constellation"
                className="inline-flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold rounded-lg transition-colors"
                data-testid="view-constellation"
              >
                <Network className="w-4 h-4" />
                Explore System Constellation
              </Link>
              <div className="relative">
                <button
                  onClick={() => setDownloadsOpen(!downloadsOpen)}
                  className="inline-flex items-center gap-1.5 px-4 py-2 border border-slate-700 text-slate-300 hover:text-white hover:border-slate-500 text-sm font-medium rounded-lg transition-colors"
                  aria-expanded={downloadsOpen}
                  data-testid="downloads-menu-button"
                >
                  <Download className="w-4 h-4" />
                  Download / Evidence
                  <ChevronDown className={`w-3.5 h-3.5 transition-transform ${downloadsOpen ? 'rotate-180' : ''}`} />
                </button>
                {downloadsOpen && (
                  <div className="absolute left-0 mt-1 w-64 rounded-lg border border-slate-700 bg-slate-900 shadow-xl z-20" role="menu">
                    {DOWNLOADS.map((d) => (
                      <a
                        key={d.href}
                        href={d.href}
                        download
                        role="menuitem"
                        className="flex items-center gap-2 px-4 py-2.5 text-sm text-slate-300 hover:bg-slate-800 hover:text-white first:rounded-t-lg last:rounded-b-lg"
                        onClick={() => setDownloadsOpen(false)}
                      >
                        <FileJson className="w-3.5 h-3.5 text-slate-500" />
                        {d.label}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </section>

          {/* ── Top consequential actions ── */}
          <section className="mb-8">
            <h2 className="text-lg font-bold text-white mb-1">Top Consequential Actions</h2>
            <p className="text-xs text-slate-500 mb-4">
              Selected from the {paths.length} evaluated action paths. Five planes are independent
              evidence states — NOT ASSESSED is not failure.
            </p>
            <div className="grid sm:grid-cols-2 gap-4">
              {topPaths.map((p) => (
                <div key={p.pathId} className="rounded-xl border border-slate-800 bg-slate-900/60 p-5">
                  <div className="text-[10px] uppercase tracking-widest text-slate-500">Business action</div>
                  <div className="text-base font-bold text-white mt-0.5">{p._desc.business}</div>
                  <div className="text-[11px] font-mono text-slate-500 mt-1 break-all">{p._desc.technical}</div>
                  <div className="mt-3 space-y-1" role="list" aria-label="Evidence planes">
                    {PLANE_ORDER.map((pl) => {
                      const st = p.planes?.[pl.key] ?? 'UNKNOWN'
                      const est = st === 'ESTABLISHED'
                      return (
                        <div key={pl.key} className="flex items-center justify-between text-[11px]">
                          <span className="text-slate-400">{pl.label}</span>
                          <span
                            className={`font-semibold ${est ? 'text-emerald-400' : 'text-slate-500'}`}
                          >
                            {est ? '● ' : '○ '}
                            {planeLabel(st)}
                          </span>
                        </div>
                      )
                    })}
                  </div>
                  <div className="mt-3 flex items-center gap-3">
                    <Link
                      href={`/sample-reports/kestrel/constellation?path=${encodeURIComponent(p.pathId)}`}
                      className="text-xs font-semibold text-emerald-400 hover:text-emerald-300 inline-flex items-center gap-1"
                      data-testid={`path-constellation-${p.pathId.slice(0, 8)}`}
                    >
                      Show in System Constellation <ArrowRight className="w-3 h-3" />
                    </Link>
                  </div>
                </div>
              ))}
            </div>
            <button
              onClick={() => setShowAllPaths(!showAllPaths)}
              className="mt-4 text-xs text-slate-400 hover:text-slate-200 underline underline-offset-2"
            >
              {showAllPaths ? 'Hide' : 'Show'} all {paths.length} evaluated action paths
            </button>
            {showAllPaths && (
              <div className="mt-3 rounded-xl border border-slate-800 bg-slate-900/60 p-4 max-h-80 overflow-y-auto">
                <table className="w-full text-[11px] text-slate-400">
                  <thead>
                    <tr className="text-left text-slate-500 uppercase tracking-wider">
                      <th className="pb-2 pr-3">Handler</th>
                      <th className="pb-2 pr-3">Sink / operation</th>
                      <th className="pb-2">Code Capable</th>
                    </tr>
                  </thead>
                  <tbody>
                    {paths.map((p) => (
                      <tr key={p.pathId} className="border-t border-slate-800/60">
                        <td className="py-1.5 pr-3 font-mono">{p.handlerRef}</td>
                        <td className="py-1.5 pr-3 font-mono break-all">{p.sinkTargetIds?.[0]}</td>
                        <td className="py-1.5 text-emerald-400 font-semibold">
                          {p.planes?.codeCapable === 'ESTABLISHED' ? 'ESTABLISHED' : p.planes?.codeCapable}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          {/* ── PARTIAL availability note (truthful) ── */}
          {data?.availability === 'PARTIAL' && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 mb-8 flex items-start gap-2 text-amber-300" role="status">
              <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
              <p className="text-xs leading-relaxed">
                Evidence coverage is partial. Bounded and unknown states below are accurate — they
                are not failures and not passes.
              </p>
            </div>
          )}

          {/* ── Canonical report (all profiles) ── */}
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-bold text-white">Full Assurance Report</h2>
            <div className="flex rounded-lg border border-slate-700 overflow-hidden" role="group" aria-label="Report profile">
              {PROFILES.map((p) => (
                <button
                  key={p.id}
                  onClick={() => setProfile(p.id)}
                  aria-pressed={profile === p.id}
                  title={p.sub}
                  className={`px-3 py-1.5 text-xs font-medium ${
                    profile === p.id ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                  data-testid={`profile-${p.id}`}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
          <p className="text-[11px] text-slate-500 mb-3">
            {PROFILES.find((p) => p.id === profile)?.sub} — same evaluation, different presentation.
          </p>
          <div className="bg-white rounded-xl overflow-hidden p-4 sm:p-8">
            <AssuranceBundleReport bundle={bundle} profile={profile} aiSystemDisplayName={data?.aiSystemDisplayName} />
          </div>

          <p className="mt-6 text-[11px] text-slate-600 text-center">
            Generated by HAIEC Evidence-Bound Assurance · Evaluation ref {String(identity.publicEvaluationRef)} ·
            Snapshot {String(identity.evaluationSnapshotAt)} · Source commit {String(identity.sourceCommitSha)}
          </p>
        </div>
      )}
    </div>
  )
}
