import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sample Reports | HAIEC — See What You\'ll Receive',
  description: 'Preview enterprise-grade compliance reports, trust artifacts, and evidence bundles generated by HAIEC. SOC 2, NYC LL144, AI Security — see real output before you buy.',
  keywords: [
    'sample compliance reports',
    'SOC 2 audit report example',
    'NYC LL144 bias audit sample',
    'AI compliance evidence bundle',
    'trust artifact preview',
    'HAIEC sample output',
  ],
  openGraph: {
    title: 'Sample Reports | HAIEC',
    description: 'Preview enterprise-grade compliance reports, trust artifacts, and evidence bundles. See real output before you buy.',
    type: 'website',
    url: 'https://www.haiec.com/sample-reports',
  },
}
