/**
 * Artifact Manifest (OUTPUT-5).
 *
 * Stable manifest for generated assurance artifacts.
 * Hashes are over actual bytes; no stronger immutability is claimed.
 */

import { createHash } from 'crypto';
import type { ArtifactPublicationState } from './artifact-publication-state';

export interface ArtifactManifestEntry {
  name: string;
  artifactType: string;
  schemaVersion: string;
  evaluationId: string;
  scanId: string;
  repositoryCommit: string | null;
  outputGeneratorBuildCommit: string;
  analyzerBuildAvailable: boolean;
  publicationState: ArtifactPublicationState;
  publicationTransitionReceipt?: string;
  generatedTimestamp: string;
  byteSize: number;
  sha256: string;
}

export interface ArtifactManifest {
  manifestSchemaVersion: string;
  generatedAt: string;
  evaluationId: string;
  scanId: string;
  repositoryCommit: string | null;
  artifacts: ArtifactManifestEntry[];
  limitations: string[];
}

export interface ArtifactManifestInput {
  name: string;
  artifactType: string;
  schemaVersion: string;
  bytes: Buffer;
}

export function computeArtifactSha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

export function buildArtifactManifest(
  artifacts: ArtifactManifestInput[],
  input: {
    evaluationId: string;
    scanId: string;
    repositoryCommit: string | null;
    outputGeneratorBuildCommit: string;
    analyzerBuildAvailable: boolean;
    generatedTimestamp: string;
  },
): ArtifactManifest {
  const entries: ArtifactManifestEntry[] = artifacts.map((a) => ({
    name: a.name,
    artifactType: a.artifactType,
    schemaVersion: a.schemaVersion,
    evaluationId: input.evaluationId,
    scanId: input.scanId,
    repositoryCommit: input.repositoryCommit,
    outputGeneratorBuildCommit: input.outputGeneratorBuildCommit,
    analyzerBuildAvailable: input.analyzerBuildAvailable,
    publicationState: 'PRIVATE_GENERATED',
    generatedTimestamp: input.generatedTimestamp,
    byteSize: a.bytes.length,
    sha256: computeArtifactSha256(a.bytes),
  }));

  return {
    manifestSchemaVersion: 'artifact-0.1.0',
    generatedAt: input.generatedTimestamp,
    evaluationId: input.evaluationId,
    scanId: input.scanId,
    repositoryCommit: input.repositoryCommit,
    artifacts: entries,
    limitations: [
      'SHA-256 is computed over the generated bytes shown to the customer.',
      'Manifest does not claim runtime immutability of source code.',
    ],
  };
}

/**
 * Machine-readable assurance output (OUTPUT-5).
 *
 * Deterministic semantic artifact derived from the shared composer.
 * Avoids implementation-private fields.
 */
export interface MachineReadableAssuranceOutput {
  schemaVersion: string;
  generatedAt: string;
  evaluationIdentity: {
    evaluationId: string;
    organizationId: string;
    aiSystemId: string;
    orchestratorRunId: string;
    exactScanId: string;
    repositoryCommitSha: string | null;
  };
  buildProvenance: {
    outputGeneratorBuildIdentity: {
      commitSha: string;
      commitRef: string;
      buildTimestamp: string;
      packageVersion: string;
    };
    analyzerBuildIdentity: {
      available: boolean;
      reason: string;
    };
    schemaVersions: Record<string, string>;
  };
  executionArchetype: {
    schemaVersion: string;
    scanId: string;
    dimensions: { facet: string; values: string[] }[];
    consequencePathSummary: {
      toolCandidateId?: string;
      handlerRef?: string;
      state: string;
      stages: string[];
    }[];
    unresolvedFrontiers: { facet: string; value: string; state: string; reasonCode: string }[];
    sourceLocationProvenance: { status: string; resolvedCount: number; totalCount: number };
    coverageSummary: { overall: string; families?: Record<string, string> };
  };
  evidenceFrontier: {
    total: number;
    byState: Record<string, number>;
    byReasonCode: Record<string, number>;
    ariFamilyFrontiers: { family: string; state: string }[];
  };
}

export function buildMachineReadableAssuranceOutput(
  output: {
    schemaVersion: string;
    evaluationIdentity: MachineReadableAssuranceOutput['evaluationIdentity'];
    buildProvenance: MachineReadableAssuranceOutput['buildProvenance'];
    executionArchetype: {
      schemaVersion: string;
      scanId: string;
      dimensions: { facet: string; values: { value: string }[] }[];
      consequencePathSummary: { toolCandidateId?: string; handlerRef?: string; state: string; stages: { stage: string }[] }[];
      unresolvedFrontiers: { facet: string; value: string; state: string; reasonCode: string }[];
      sourceLocationProvenance: { status: string; resolvedCount: number; totalCount: number };
      coverageSummary: { overall: string; families?: Record<string, string> };
    };
    evidenceFrontier: {
      summary: { totalFrontiers: number; byState: Record<string, number>; byReasonCode: Record<string, number> };
      ariFamilyFrontiers: { family: string; state: string }[];
    };
  },
  generatedAt: string,
): MachineReadableAssuranceOutput {
  return {
    schemaVersion: 'machine-readable-0.1.0',
    generatedAt,
    evaluationIdentity: output.evaluationIdentity,
    buildProvenance: output.buildProvenance,
    executionArchetype: {
      schemaVersion: output.executionArchetype.schemaVersion,
      scanId: output.executionArchetype.scanId,
      dimensions: output.executionArchetype.dimensions.map((d) => ({
        facet: d.facet,
        values: d.values.map((v) => v.value),
      })),
      consequencePathSummary: output.executionArchetype.consequencePathSummary.map((p) => ({
        toolCandidateId: p.toolCandidateId,
        handlerRef: p.handlerRef,
        state: p.state,
        stages: p.stages.map((s) => s.stage),
      })),
      unresolvedFrontiers: output.executionArchetype.unresolvedFrontiers,
      sourceLocationProvenance: output.executionArchetype.sourceLocationProvenance,
      coverageSummary: output.executionArchetype.coverageSummary,
    },
    evidenceFrontier: {
      total: output.evidenceFrontier.summary.totalFrontiers,
      byState: output.evidenceFrontier.summary.byState,
      byReasonCode: output.evidenceFrontier.summary.byReasonCode,
      ariFamilyFrontiers: output.evidenceFrontier.ariFamilyFrontiers,
    },
  };
}
