/**
 * Artifact Manifest (OUTPUT-5).
 *
 * Stable manifest for generated assurance artifacts.
 * Hashes are over actual bytes; no stronger immutability is claimed.
 */

import { createHash } from 'crypto';
import type { ArtifactPublicationState } from './artifact-publication-state';
import type { ActionProofReportSection, AgentReachabilityReportSection, ActionAssuranceReportSection } from './u6-types';
import type { EvaluatedAssuranceOutput } from './assurance-output-composer';

export interface ArtifactManifestEntry {
  name: string;
  artifactType: string;
  schemaVersion: string;
  evaluationId: string;
  scanId: string;
  repositoryCommit: string | null;
  outputGeneratorBuildCommit: string;
  analyzerBuildAvailable: boolean;
  publicationState: ArtifactPublicationState;
  publicationTransitionReceipt?: string;
  generatedTimestamp: string;
  byteSize: number;
  sha256: string;
}

export interface ArtifactManifest {
  manifestSchemaVersion: string;
  generatedAt: string;
  evaluationId: string;
  scanId: string;
  repositoryCommit: string | null;
  artifacts: ArtifactManifestEntry[];
  limitations: string[];
}

export interface ArtifactManifestInput {
  name: string;
  artifactType: string;
  schemaVersion: string;
  bytes: Buffer;
}

export function computeArtifactSha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

export function buildArtifactManifest(
  artifacts: ArtifactManifestInput[],
  input: {
    evaluationId: string;
    scanId: string;
    repositoryCommit: string | null;
    outputGeneratorBuildCommit: string;
    analyzerBuildAvailable: boolean;
    generatedTimestamp: string;
  },
): ArtifactManifest {
  const entries: ArtifactManifestEntry[] = artifacts.map((a) => ({
    name: a.name,
    artifactType: a.artifactType,
    schemaVersion: a.schemaVersion,
    evaluationId: input.evaluationId,
    scanId: input.scanId,
    repositoryCommit: input.repositoryCommit,
    outputGeneratorBuildCommit: input.outputGeneratorBuildCommit,
    analyzerBuildAvailable: input.analyzerBuildAvailable,
    publicationState: 'PRIVATE_GENERATED',
    generatedTimestamp: input.generatedTimestamp,
    byteSize: a.bytes.length,
    sha256: computeArtifactSha256(a.bytes),
  }));

  return {
    manifestSchemaVersion: 'artifact-0.1.0',
    generatedAt: input.generatedTimestamp,
    evaluationId: input.evaluationId,
    scanId: input.scanId,
    repositoryCommit: input.repositoryCommit,
    artifacts: entries,
    limitations: [
      'SHA-256 is computed over the generated bytes shown to the customer.',
      'Manifest does not claim runtime immutability of source code.',
    ],
  };
}

/**
 * Machine-readable assurance output (OUTPUT-5).
 *
 * Deterministic semantic artifact derived from the shared composer.
 * Avoids implementation-private fields.
 */
export interface MachineReadableAssuranceOutput {
  schemaVersion: string;
  generatedAt: string;
  evaluationIdentity: {
    evaluationId: string;
    organizationId: string;
    aiSystemId: string;
    orchestratorRunId: string;
    exactScanId: string;
    repositoryCommitSha: string | null;
  };
  buildProvenance: {
    outputGeneratorBuildIdentity: {
      commitSha: string;
      commitRef: string;
      buildTimestamp: string;
      packageVersion: string;
    };
    analyzerBuildIdentity: {
      available: boolean;
      reason: string;
    };
    schemaVersions: Record<string, string>;
  };
  executionArchetype: {
    schemaVersion: string;
    scanId: string;
    dimensions: {
      facet: string;
      values: {
        subject: { kind: string; id: string; displayName?: string };
        value: string;
        valueSet?: string[];
        state: string;
        coverage: string;
        evidenceRefs: string[];
        sourceRelationIds: string[];
        limitations: string[];
      }[];
    }[];
    consequencePathSummary: {
      toolCandidateId?: string;
      handlerRef?: string;
      consequenceId?: string;
      state: string;
      coverage: string;
      limitations: string[];
      stages: {
        stage: string;
        state: string;
        relationId: string;
        toolCandidateId?: string;
        handlerRef?: string;
        targetId?: string;
        limitations: string[];
      }[];
    }[];
    unresolvedFrontiers: { facet: string; value: string; state: string; reasonCode: string }[];
    sourceLocationProvenance: { status: string; resolvedCount: number; totalCount: number };
    coverageSummary: { overall: string; families?: Record<string, string> };
  };
  evidenceFrontier: {
    total: number;
    byState: Record<string, number>;
    byReasonCode: Record<string, number>;
    ariFamilyFrontiers: { family: string; state: string }[];
  };
  actionProof: ActionProofReportSection;
  reachability: AgentReachabilityReportSection;
  actionAssurance: ActionAssuranceReportSection;
}

export function buildMachineReadableAssuranceOutput(
  output: EvaluatedAssuranceOutput,
  generatedAt: string,
): MachineReadableAssuranceOutput {
  const frontierItems = output.evidenceFrontier.frontierItems ?? [];

  return {
    schemaVersion: 'machine-readable-0.1.0',
    generatedAt,
    evaluationIdentity: output.evaluationIdentity,
    buildProvenance: output.buildProvenance,
    executionArchetype: {
      schemaVersion: output.executionArchetype.schemaVersion,
      scanId: output.executionArchetype.scanId,
      dimensions: output.executionArchetype.dimensions.map((d) => ({
        facet: d.facet,
        values: d.values.map((v) => ({
          subject: {
            kind: v.subject.kind,
            id: v.subject.id,
            displayName: v.subject.displayName,
          },
          value: v.value,
          valueSet: v.valueSet,
          state: v.state,
          coverage: v.coverage,
          evidenceRefs: v.evidenceRefs,
          sourceRelationIds: v.sourceRelationIds,
          limitations: v.limitations,
        })),
      })),
      consequencePathSummary: output.executionArchetype.consequencePathSummary.map((p) => ({
        toolCandidateId: p.toolCandidateId,
        handlerRef: p.handlerRef,
        consequenceId: p.consequenceId,
        state: p.state,
        coverage: p.coverage,
        limitations: p.limitations,
        stages: p.stages.map((s) => ({
          stage: s.stage,
          state: s.state,
          relationId: s.relationId,
          toolCandidateId: s.toolCandidateId,
          handlerRef: s.handlerRef,
          targetId: s.targetId,
          limitations: s.limitations,
        })),
      })),
      unresolvedFrontiers: frontierItems.map((f) => ({
        facet: f.facet,
        value: f.value,
        state: f.state,
        reasonCode: f.reasonCode,
      })),
      sourceLocationProvenance: output.executionArchetype.sourceLocationProvenance,
      coverageSummary: output.executionArchetype.coverageSummary,
    },
    evidenceFrontier: {
      total: output.evidenceFrontier.summary.totalFrontiers,
      byState: output.evidenceFrontier.summary.byState,
      byReasonCode: output.evidenceFrontier.summary.byReasonCode,
      ariFamilyFrontiers: output.evidenceFrontier.ariFamilyFrontiers,
    },
    actionProof: output.actionProof,
    reachability: output.reachability,
    actionAssurance: output.actionAssurance,
  };
}
