'use client'

/**
 * Kestrel — Release Comparison (public explainer).
 *
 * Renders the SANITIZED public projection of the frozen A/B-8 Release A /
 * Release B consequence-delta comparison
 * (/demo/kestrel/kestrel-compare.public.json), generated by
 * scripts/kestrel-compare-export.ts through the canonical
 * buildConsequenceDeltaForEvaluations owner. This page does not
 * re-evaluate, rescan, or fabricate evidence.
 *
 * This is an explainer + navigation surface. The authoritative evidence
 * package lives in the judge Google Drive folder; the authenticated
 * judge workspace remains the product source of truth.
 */

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { JUDGE_EVIDENCE } from '@/data/kestrel-demo/judge-evidence'
import {
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  GitCompare,
  Loader2,
  Lock,
  Network,
  Scale,
} from 'lucide-react'

type EstablishedItem = { handler: string; access: string; operation: string; surface: string }

type ComparePayload = {
  projectionVersion: string
  system: { displayName: string; publicRef: string }
  comparison: {
    comparisonDigest: string
    overallResult: string
    baseline: { label: string; evaluationRef: string; commitSha: string; snapshotAt?: string }
    candidate: { label: string; evaluationRef: string; commitSha: string; snapshotAt?: string }
    comparability: {
      releasePerimeter: string
      analyzer: string
      scopeState: string
      scopeNote: string
      repeatability: string
    }
    summary: {
      totalComparedFacts: number
      establishedControlChanges: number
      unresolvedFacts: number
      unexpectedEstablishedChanges: number
    }
    transition: { label: string; before: string; after: string; count: number }
    establishedItems: EstablishedItem[]
    mutations: { id: string; label: string; result: string }[]
  }
  navigation: {
    baselineReport: string
    consequenceMap: string
    orderRecordWrite: string
    judgeLogin: string
  }
}

const mono = 'font-mono tracking-widest uppercase'

function StatTile({ value, label, tone = 'slate' }: { value: string; label: string; tone?: 'slate' | 'emerald' | 'amber' }) {
  const colors = {
    slate: 'text-slate-200',
    emerald: 'text-emerald-300',
    amber: 'text-amber-300',
  }[tone]
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/60 px-5 py-4">
      <div className={`text-2xl font-extrabold tracking-tight ${colors}`}>{value}</div>
      <div className={`mt-1 text-[10px] ${mono} text-slate-500`}>{label}</div>
    </div>
  )
}

function CtaButton({ href, children, external, primary }: { href: string; children: React.ReactNode; external?: boolean; primary?: boolean }) {
  const cls = primary
    ? 'inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-emerald-400 transition-colors'
    : 'inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/60 px-4 py-2.5 text-sm font-medium text-slate-200 hover:border-slate-500 hover:text-white transition-colors'
  if (external) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className={cls}>
        {children}
        <ExternalLink className="w-3.5 h-3.5" />
      </a>
    )
  }
  return (
    <Link href={href} className={cls}>
      {children}
      <ArrowRight className="w-3.5 h-3.5" />
    </Link>
  )
}

export default function KestrelComparePage() {
  const [data, setData] = useState<ComparePayload | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch('/demo/kestrel/kestrel-compare.public.json')
      .then((r) => {
        if (!r.ok) throw new Error(`projection ${r.status}`)
        return r.json()
      })
      .then(setData)
      .catch((e) => setError(e.message))
  }, [])

  if (error) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="rounded-lg border border-red-900/60 bg-red-950/30 p-5 text-sm text-red-300">
          Comparison projection unavailable — {error}
        </div>
      </div>
    )
  }
  if (!data) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center gap-2 text-slate-400 text-sm">
        <Loader2 className="w-4 h-4 animate-spin" /> Loading sanitized comparison…
      </div>
    )
  }

  const { comparison: c, navigation: nav } = data
  const digestShort = c.comparisonDigest.slice(0, 12)
  const handlers = [...new Set(c.establishedItems.map((i) => i.handler.split(':').pop()))]
  const surfaces = [...new Set(c.establishedItems.map((i) => `${i.access} → ${i.surface}`))]

  return (
    <div className="min-h-screen bg-slate-950">
      {/* SECTION 1 — header */}
      <div className="border-b border-slate-800/60 bg-slate-950/90">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 pt-24 pb-8">
          <Link
            href="/sample-reports/kestrel"
            className="inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-300 mb-6"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Kestrel assurance report
          </Link>
          <div className="flex flex-wrap items-center gap-2 mb-4">
            <span className="inline-flex items-center px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-[11px] font-medium">
              MunichTech EXPO 2026 Demo Evidence
            </span>
            <span className={`text-[11px] ${mono} text-slate-500`}>Sanitized public projection</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">
            Kestrel — Release Comparison
          </h1>
          <p className="mt-3 text-slate-400 max-w-3xl text-sm leading-relaxed">
            Two completed evaluations of the same AI system, bound to two source releases.
            The question: <strong className="text-slate-200">what changed in consequence, control, and evidence?</strong>
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 pb-16">
        {/* SECTION 2 — result first */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 mt-8 mb-8">
          <div className="grid sm:grid-cols-[220px_1fr] gap-6 items-start">
            <div>
              <div className={`text-[11px] ${mono} text-slate-500 mb-1`}>Overall result</div>
              <div className="text-4xl font-extrabold text-slate-100 tracking-tight">INCONCLUSIVE</div>
              <div className="mt-1 text-[11px] text-slate-500">Not a failure — a bounded answer.</div>
            </div>
            <div>
              <p className="text-slate-200 text-sm leading-relaxed">
                The comparison established a qualified control change. Partial coverage prevents
                reliable addition or removal claims for the other mutations.
              </p>
              <p className="mt-3 text-slate-400 text-sm leading-relaxed">
                <strong className="text-slate-200">What this means:</strong> one claim is proven;
                the rest are honestly unresolved rather than invented as absence.
              </p>
            </div>
          </div>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-6">
            <StatTile value={String(c.summary.establishedControlChanges)} label="Established control changes" tone="emerald" />
            <StatTile value={String(c.summary.unresolvedFacts)} label="Unresolved facts" tone="amber" />
            <StatTile value={c.comparability.releasePerimeter} label="Release perimeter" />
            <StatTile value={c.comparability.analyzer} label="Analyzer comparability" />
          </div>
        </section>

        {/* SECTION 3 — the established change */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 mb-8">
          <div className="flex items-center gap-2 mb-4">
            <GitCompare className="w-4 h-4 text-emerald-300" />
            <h2 className={`text-xs ${mono} text-emerald-300`}>The established change</h2>
          </div>
          <div className="flex flex-wrap items-center gap-3 mb-5">
            <span className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-2 font-mono text-sm text-slate-300">
              {c.transition.before}
            </span>
            <ArrowRight className="w-4 h-4 text-emerald-400" />
            <span className="rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-4 py-2 font-mono text-sm text-emerald-200">
              {c.transition.after}
            </span>
          </div>
          <p className="text-slate-200 text-sm leading-relaxed max-w-3xl">
            {c.transition.label} remains declared and is now also bound to the source-backed
            action path — across {c.transition.count} established control changes on{' '}
            {handlers.map((h) => (
              <code key={h} className="text-emerald-300 text-[13px]">{h}</code>
            )).reduce((acc, el, i) => (i === 0 ? [el] : [...acc, ', ', el]), [] as React.ReactNode[])}.
          </p>
          <div className="mt-4 flex flex-wrap gap-2">
            {surfaces.slice(0, 8).map((surf) => (
              <span key={surf} className="rounded-md border border-slate-800 bg-slate-950 px-2.5 py-1 font-mono text-[11px] text-slate-400">
                {surf}
              </span>
            ))}
          </div>
          <p className="mt-5 text-xs text-slate-500 leading-relaxed max-w-3xl">
            This is a qualified evidence claim — not a claim that every mutation was detected
            or that the candidate is universally safer.
          </p>
        </section>

        {/* SECTION 4 — what we refused to claim */}
        <section className="rounded-2xl border border-amber-500/25 bg-amber-500/[0.04] p-6 sm:p-8 mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Scale className="w-4 h-4 text-amber-300" />
            <h2 className={`text-xs ${mono} text-amber-300`}>What we refused to claim</h2>
          </div>
          <p className="text-slate-200 text-sm leading-relaxed max-w-3xl">
            <strong className="text-amber-200">UNRESOLVED ≠ ABSENT.</strong> Partial
            dispatch-site coverage cannot establish absence — so the comparison reports
            unresolved facts instead of manufacturing removals.
          </p>
          <div className="mt-5 grid sm:grid-cols-2 gap-3">
            {c.mutations.map((m) => (
              <div key={m.id} className="rounded-lg border border-slate-800 bg-slate-950/70 px-4 py-3 flex items-center justify-between gap-3">
                <div>
                  <span className={`text-[10px] ${mono} text-slate-500`}>{m.id}</span>
                  <div className="text-sm text-slate-200 mt-0.5">{m.label}</div>
                </div>
                <span
                  className={`font-mono text-xs px-2.5 py-1 rounded border ${
                    m.result === 'ESTABLISHED'
                      ? 'border-emerald-500/40 text-emerald-300 bg-emerald-500/10'
                      : 'border-slate-700 text-slate-300 bg-slate-900'
                  }`}
                >
                  {m.result}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* SECTION 5 — why it matters */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 mb-8">
          <h2 className={`text-xs ${mono} text-slate-400 mb-4`}>Why it matters</h2>
          <p className="text-lg sm:text-xl text-slate-100 font-semibold leading-snug max-w-3xl">
            Git tells you what code changed.
            <br />
            This comparison asks what changed in consequence, control, and evidence.
          </p>
          <div className="mt-5 flex flex-wrap items-center gap-3 font-mono text-sm">
            <span className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-2 text-slate-300">CODE DIFF</span>
            <span className="text-emerald-400 font-bold">≠</span>
            <span className="rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-4 py-2 text-emerald-200">ASSURANCE DELTA</span>
          </div>
        </section>

        {/* SECTION 6 — exact releases */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 mb-8">
          <h2 className={`text-xs ${mono} text-slate-400 mb-5`}>Exact releases</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[c.baseline, c.candidate].map((r) => (
              <div key={r.evaluationRef} className="rounded-xl border border-slate-800 bg-slate-950/70 p-5">
                <div className={`text-[10px] ${mono} text-slate-500`}>{r.label} — {r.evaluationRef === c.baseline.evaluationRef ? 'baseline' : 'candidate'}</div>
                <div className="mt-2 font-mono text-sm text-slate-200">{r.evaluationRef}</div>
                <div className="mt-2 text-[11px] text-slate-500">source commit</div>
                <div className="font-mono text-xs text-emerald-300 break-all">{r.commitSha}</div>
              </div>
            ))}
          </div>
          <div className="mt-5 grid grid-cols-3 gap-3">
            <StatTile value={c.comparability.releasePerimeter} label="Release perimeter" />
            <StatTile value={c.comparability.analyzer} label="Analyzer" />
            <StatTile value={c.comparability.repeatability} label="Repeatability" />
          </div>
          <p className="mt-4 text-xs text-slate-500 leading-relaxed max-w-3xl">
            {c.comparability.scopeNote} Comparison digest:{' '}
            <code className="text-slate-400">{digestShort}…</code>
          </p>
        </section>

        {/* SECTION 7 — continue the judge path */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8">
          <div className="flex items-center gap-2 mb-5">
            <Network className="w-4 h-4 text-emerald-300" />
            <h2 className={`text-xs ${mono} text-emerald-300`}>Continue the judge path</h2>
          </div>
          <div className="flex flex-wrap gap-3">
            <CtaButton href={nav.baselineReport}>View baseline assurance report</CtaButton>
            <CtaButton href={nav.consequenceMap}>View consequence map</CtaButton>
            <CtaButton href={nav.orderRecordWrite}>View ORDER RECORD WRITE</CtaButton>
            {JUDGE_EVIDENCE.url ? (
              <CtaButton href={JUDGE_EVIDENCE.url} external primary>
                Open official judge evidence
              </CtaButton>
            ) : (
              <div className="inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/60 px-4 py-2.5 text-sm text-slate-400">
                <ExternalLink className="w-3.5 h-3.5" />
                {JUDGE_EVIDENCE.folderLabel}
              </div>
            )}
          </div>
          {!JUDGE_EVIDENCE.url && (
            <p className="mt-3 text-xs text-slate-500">
              {JUDGE_EVIDENCE.note} Artifact: <code className="text-slate-400">{JUDGE_EVIDENCE.artifactPath}</code>
            </p>
          )}
          <div className="mt-6 pt-5 border-t border-slate-800">
            <CtaButton href={nav.judgeLogin}>
              <Lock className="w-3.5 h-3.5" /> Try the read-only judge workspace
            </CtaButton>
            <p className="mt-2 text-[11px] text-slate-500">
              Private judge credentials supplied separately. Read-only review account —
              please do not run new evaluations or change configuration.
            </p>
          </div>
          <p className="mt-6 text-[11px] text-slate-600">
            Frozen experiment record (A/B-8) · projection {data.projectionVersion} · no live-system state shown.
          </p>
        </section>
      </div>
    </div>
  )
}
